### ISSUE TITLE
初回起動時に落ちるバグの修正

### ISSUE THREAD

**Issue by atomic928** [EinStealth/Android#17]
RelativeTimeが無くて怒られてる
最初に適当なデフォルト値入れておく必要がある

FATAL EXCEPTION: main
                                                                                                    Process: com.example.hideandseek, PID: 27289
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property relativeTime has not been initialized
                                                                                                    	at com.example.hideandseek.ui.viewmodel.MainActivityViewModel.getRelativeTime(MainActivityViewModel.kt:27)
                                                                                                    	at com.example.hideandseek.ui.viewmodel.MainActivityViewModel.calculateRelativeTime(MainActivityViewModel.kt:35)
                                                                                                    	at com.example.hideandseek.ui.view.MainActivity.postCalculatedRelativeTime(MainActivity.kt:150)
                                                                                                    	at com.example.hideandseek.ui.view.MainActivity.access$postCalculatedRelativeTime(MainActivity.kt:25)
                                                                                                    	at com.example.hideandseek.ui.view.MainActivity$onCreate$2.onLocationResult(MainActivity.kt:128)
                                                                                                    	at com.google.android.gms.internal.location.zzct.notifyListener(com.google.android.gms:play-services-location@@21.0.1:2)
                                                                                                    	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.1.0:2)
                                                                                                    	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by atomic928** [comment]
relativeTimeの取り方修正したので解決
